//
//  NoZ Game Engine - Copyright(c) 2025 NoZ Games, LLC
//

#pragma once

enum InputCode
{
    INPUT_CODE_NONE = 0,

    // MOUSE BUTTONS
    MOUSE_LEFT,
    MOUSE_RIGHT,
    MOUSE_MIDDLE,
    MOUSE_BUTTON_4,
    MOUSE_BUTTON_5,

    // MOUSE AXES
    MOUSE_X,
    MOUSE_Y,
    MOUSE_SCROLL_X,
    MOUSE_SCROLL_Y,

    // KEYBOARD KEYS (MOST COMMON ONES, CAN BE EXPANDED)
    KEY_A, KEY_B, KEY_C, KEY_D, KEY_E, KEY_F, KEY_G, KEY_H, KEY_I, KEY_J, KEY_K, KEY_L, KEY_M,
    KEY_N, KEY_O, KEY_P, KEY_Q, KEY_R, KEY_S, KEY_T, KEY_U, KEY_V, KEY_W, KEY_X, KEY_Y, KEY_Z,

    KEY_0, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9,

    KEY_SEMICOLON,
    KEY_MINUS,
    KEY_EQUALS,

    KEY_LEFT_BRACKET,
    KEY_RIGHT_BRACKET,

    KEY_SPACE,
    KEY_ENTER,
    KEY_TAB,
    KEY_COMMA,
    KEY_PERIOD,
    KEY_BACKSPACE,
    KEY_ESCAPE,

    KEY_LEFT_SHIFT,
    KEY_LEFT_CTRL,
    KEY_LEFT_ALT,
    KEY_RIGHT_SHIFT,
    KEY_RIGHT_CTRL,
    KEY_RIGHT_ALT,

    KEY_UP,
    KEY_DOWN,
    KEY_LEFT,
    KEY_RIGHT,

    KEY_F1, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6,
    KEY_F7, KEY_F8, KEY_F9, KEY_F10, KEY_F11, KEY_F12,

    // GAMEPAD BUTTONS (WORKS FOR ANY CONNECTED GAMEPAD)
    GAMEPAD_A,           // CROSS ON PS, A ON XBOX
    GAMEPAD_B,           // CIRCLE ON PS, B ON XBOX
    GAMEPAD_X,           // SQUARE ON PS, X ON XBOX
    GAMEPAD_Y,           // TRIANGLE ON PS, Y ON XBOX

    GAMEPAD_LEFT_SHOULDER,
    GAMEPAD_RIGHT_SHOULDER,
    GAMEPAD_LEFT_TRIGGER_BUTTON,  // L2/LT PRESSED AS BUTTON
    GAMEPAD_RIGHT_TRIGGER_BUTTON, // R2/RT PRESSED AS BUTTON

    GAMEPAD_START,
    GAMEPAD_BACK,        // SELECT/VIEW
    GAMEPAD_GUIDE,       // PS/XBOX BUTTON

    GAMEPAD_LEFT_STICK_BUTTON,
    GAMEPAD_RIGHT_STICK_BUTTON,

    GAMEPAD_DPAD_UP,
    GAMEPAD_DPAD_DOWN,
    GAMEPAD_DPAD_LEFT,
    GAMEPAD_DPAD_RIGHT,

    // GAMEPAD AXES
    GAMEPAD_LEFT_STICK_X,
    GAMEPAD_LEFT_STICK_Y,
    GAMEPAD_RIGHT_STICK_X,
    GAMEPAD_RIGHT_STICK_Y,
    GAMEPAD_LEFT_TRIGGER,   // 0 TO 1
    GAMEPAD_RIGHT_TRIGGER,  // 0 TO 1

    // SPECIFIC GAMEPAD VERSIONS (FOR WHEN YOU NEED A SPECIFIC CONTROLLER)
    GAMEPAD_1_A, GAMEPAD_1_B, GAMEPAD_1_X, GAMEPAD_1_Y,
    GAMEPAD_1_LEFT_SHOULDER, GAMEPAD_1_RIGHT_SHOULDER,
    GAMEPAD_1_START, GAMEPAD_1_BACK,
    GAMEPAD_1_LEFT_STICK_BUTTON, GAMEPAD_1_RIGHT_STICK_BUTTON,
    GAMEPAD_1_DPAD_UP, GAMEPAD_1_DPAD_DOWN, GAMEPAD_1_DPAD_LEFT, GAMEPAD_1_DPAD_RIGHT,
    GAMEPAD_1_LEFT_STICK_X, GAMEPAD_1_LEFT_STICK_Y,
    GAMEPAD_1_RIGHT_STICK_X, GAMEPAD_1_RIGHT_STICK_Y,
    GAMEPAD_1_LEFT_TRIGGER, GAMEPAD_1_RIGHT_TRIGGER,

    GAMEPAD_2_A, GAMEPAD_2_B, GAMEPAD_2_X, GAMEPAD_2_Y,
    GAMEPAD_2_LEFT_SHOULDER, GAMEPAD_2_RIGHT_SHOULDER,
    GAMEPAD_2_START, GAMEPAD_2_BACK,
    GAMEPAD_2_LEFT_STICK_BUTTON, GAMEPAD_2_RIGHT_STICK_BUTTON,
    GAMEPAD_2_DPAD_UP, GAMEPAD_2_DPAD_DOWN, GAMEPAD_2_DPAD_LEFT, GAMEPAD_2_DPAD_RIGHT,
    GAMEPAD_2_LEFT_STICK_X, GAMEPAD_2_LEFT_STICK_Y,
    GAMEPAD_2_RIGHT_STICK_X, GAMEPAD_2_RIGHT_STICK_Y,
    GAMEPAD_2_LEFT_TRIGGER, GAMEPAD_2_RIGHT_TRIGGER,

    GAMEPAD_3_A, GAMEPAD_3_B, GAMEPAD_3_X, GAMEPAD_3_Y,
    GAMEPAD_3_LEFT_SHOULDER, GAMEPAD_3_RIGHT_SHOULDER,
    GAMEPAD_3_START, GAMEPAD_3_BACK,
    GAMEPAD_3_LEFT_STICK_BUTTON, GAMEPAD_3_RIGHT_STICK_BUTTON,
    GAMEPAD_3_DPAD_UP, GAMEPAD_3_DPAD_DOWN, GAMEPAD_3_DPAD_LEFT, GAMEPAD_3_DPAD_RIGHT,
    GAMEPAD_3_LEFT_STICK_X, GAMEPAD_3_LEFT_STICK_Y,
    GAMEPAD_3_RIGHT_STICK_X, GAMEPAD_3_RIGHT_STICK_Y,
    GAMEPAD_3_LEFT_TRIGGER, GAMEPAD_3_RIGHT_TRIGGER,

    GAMEPAD_4_A, GAMEPAD_4_B, GAMEPAD_4_X, GAMEPAD_4_Y,
    GAMEPAD_4_LEFT_SHOULDER, GAMEPAD_4_RIGHT_SHOULDER,
    GAMEPAD_4_START, GAMEPAD_4_BACK,
    GAMEPAD_4_LEFT_STICK_BUTTON, GAMEPAD_4_RIGHT_STICK_BUTTON,
    GAMEPAD_4_DPAD_UP, GAMEPAD_4_DPAD_DOWN, GAMEPAD_4_DPAD_LEFT, GAMEPAD_4_DPAD_RIGHT,
    GAMEPAD_4_LEFT_STICK_X, GAMEPAD_4_LEFT_STICK_Y,
    GAMEPAD_4_RIGHT_STICK_X, GAMEPAD_4_RIGHT_STICK_Y,
    GAMEPAD_4_LEFT_TRIGGER, GAMEPAD_4_RIGHT_TRIGGER,

    INPUT_CODE_COUNT
};

inline bool IsKeyboard(InputCode code) {
    return code >= KEY_A && code <= KEY_F12;
}

inline bool IsMouse(InputCode code) {
    return code >= MOUSE_LEFT && code <= MOUSE_SCROLL_Y;
}

inline bool IsGamepad(InputCode code) {
    return code >= GAMEPAD_A && code <= GAMEPAD_4_RIGHT_TRIGGER;
}

inline bool IsAxis(InputCode code) {
    return code == MOUSE_X || code == MOUSE_Y ||
        code == MOUSE_SCROLL_X || code == MOUSE_SCROLL_Y ||
        (code >= GAMEPAD_LEFT_STICK_X && code <= GAMEPAD_RIGHT_TRIGGER) ||
        (code >= GAMEPAD_1_LEFT_STICK_X && code <= GAMEPAD_1_RIGHT_TRIGGER) ||
        (code >= GAMEPAD_2_LEFT_STICK_X && code <= GAMEPAD_2_RIGHT_TRIGGER) ||
        (code >= GAMEPAD_3_LEFT_STICK_X && code <= GAMEPAD_3_RIGHT_TRIGGER) ||
        (code >= GAMEPAD_4_LEFT_STICK_X && code <= GAMEPAD_4_RIGHT_TRIGGER);
}

inline bool IsButton(InputCode code)
{
    return !IsAxis(code) && code != INPUT_CODE_NONE;
}
