//
//  NoZ Game Engine - Copyright(c) 2025 NoZ Games, LLC
//

#pragma once

#define EDITOR_TYPES \
EDITOR_TYPE(TSTRING) \
EDITOR_TYPE(TSTRING_BUILDER) \
EDITOR_TYPE(VIEW) \
EDITOR_TYPE(LOG_VIEW) \
EDITOR_TYPE(TREE_VIEW) \
EDITOR_TYPE(TREE_VIEW_NODE) \
EDITOR_TYPE(INSPECTOR_VIEW) \
EDITOR_TYPE(INSPECTOR_OBJECT) \

enum EditorTypes
{
    EDITOR_TYPE_UNKNOWN = TYPE_EDITOR,
#define EDITOR_TYPE(type) EDITOR_TYPE_##type,
    EDITOR_TYPES
#undef EDITOR_TYPE
};
