//
// Auto-generated asset header - DO NOT EDIT MANUALLY
// Generated by NoZ Game Engine Asset Importer
//

#include <noz/noz.h>
#include "nozed_assets.h"

#if defined(NOZ_BUILTIN_ASSETS)
#include "nozed_assets_build.cpp"
#endif

// @externs
extern int MESH_COUNT;
extern int TEXTURE_COUNT;
extern int FONT_COUNT;
extern int SHADER_COUNT;

// @Mesh
Mesh* MESH_ASSET_ICON_BIN = nullptr;
Mesh* MESH_ICON_PALETTE = nullptr;
Mesh* MESH_ASSET_ICON_EVENT = nullptr;
Mesh* MESH_ICON_TILING = nullptr;
Mesh* MESH_ICON_ROOT_MOTION = nullptr;
Mesh* MESH_ICON_PUBLISH = nullptr;
Mesh* MESH_ICON_ONION = nullptr;
Mesh* MESH_ICON_MIRROR = nullptr;
Mesh* MESH_ICON_LOOP = nullptr;
Mesh* MESH_ICON_EXPAND_UP = nullptr;
Mesh* MESH_ICON_EXPAND_DOWN = nullptr;
Mesh* MESH_ICON_DROPDOWN = nullptr;
Mesh* MESH_ASSET_ICON_VFX = nullptr;
Mesh* MESH_ASSET_ICON_SOUND = nullptr;
Mesh* MESH_ASSET_ICON_SHADER = nullptr;
Mesh* MESH_ASSET_ICON_LUA = nullptr;
Mesh* MESH_ASSET_ICON_FONT = nullptr;

// @Texture
Texture* TEXTURE_TEST = nullptr;
Texture* TEXTURE_EDITOR_PALETTE = nullptr;

// @Font
Font* FONT_SEGUISB = nullptr;

// @Shader
Shader* SHADER_VFX = nullptr;
Shader* SHADER_UI_VIGNETTE = nullptr;
Shader* SHADER_UI_IMAGE_TEXTURE = nullptr;
Shader* SHADER_UI_IMAGE = nullptr;
Shader* SHADER_UI = nullptr;
Shader* SHADER_TEXTURED_MESH = nullptr;
Shader* SHADER_TEXT = nullptr;
Shader* SHADER_SOLID = nullptr;
Shader* SHADER_SKINNED_MESH = nullptr;
Shader* SHADER_POSTPROCESS_UI_COMPOSITE = nullptr;
Shader* SHADER_POSTPROCESS_DESATURATE = nullptr;
Shader* SHADER_MESH = nullptr;
Shader* SHADER_EDITOR = nullptr;

// @name
const Name* NAME_MESH = nullptr;
const Name* NAME_VFX = nullptr;
const Name* NAME_ANIMATION = nullptr;
const Name* NAME_ATLAS = nullptr;
const Name* NAME_M = nullptr;
const Name* NAME_ANIMATEDMESH = nullptr;
const Name* NAME_EDIT = nullptr;
const Name* NAME_RENAME = nullptr;
const Name* NAME_N = nullptr;
const Name* NAME_S = nullptr;
const Name* NAME_SAVE = nullptr;
const Name* NAME_AM = nullptr;
const Name* NAME_BUILD = nullptr;
const Name* NAME_EVENT = nullptr;
const Name* NAME_E = nullptr;
const Name* NAME_NEW = nullptr;
const Name* NAME_R = nullptr;
const Name* NAME_B = nullptr;
const Name* NAME_MIRROR = nullptr;
const Name* NAME_SKELETON = nullptr;
const Name* NAME_RU = nullptr;
const Name* NAME_A = nullptr;

// @path
const Name* PATH_MESH_ASSET_ICON_BIN = nullptr;
const Name* PATH_MESH_ICON_PALETTE = nullptr;
const Name* PATH_FONT_SEGUISB = nullptr;
const Name* PATH_TEXTURE_TEST = nullptr;
const Name* PATH_SHADER_VFX = nullptr;
const Name* PATH_SHADER_UI_VIGNETTE = nullptr;
const Name* PATH_SHADER_UI_IMAGE_TEXTURE = nullptr;
const Name* PATH_SHADER_UI_IMAGE = nullptr;
const Name* PATH_SHADER_UI = nullptr;
const Name* PATH_SHADER_TEXTURED_MESH = nullptr;
const Name* PATH_SHADER_TEXT = nullptr;
const Name* PATH_SHADER_SOLID = nullptr;
const Name* PATH_SHADER_SKINNED_MESH = nullptr;
const Name* PATH_SHADER_POSTPROCESS_UI_COMPOSITE = nullptr;
const Name* PATH_SHADER_POSTPROCESS_DESATURATE = nullptr;
const Name* PATH_TEXTURE_EDITOR_PALETTE = nullptr;
const Name* PATH_MESH_ASSET_ICON_EVENT = nullptr;
const Name* PATH_SHADER_MESH = nullptr;
const Name* PATH_SHADER_EDITOR = nullptr;
const Name* PATH_MESH_ICON_TILING = nullptr;
const Name* PATH_MESH_ICON_ROOT_MOTION = nullptr;
const Name* PATH_MESH_ICON_PUBLISH = nullptr;
const Name* PATH_MESH_ICON_ONION = nullptr;
const Name* PATH_MESH_ICON_MIRROR = nullptr;
const Name* PATH_MESH_ICON_LOOP = nullptr;
const Name* PATH_MESH_ICON_EXPAND_UP = nullptr;
const Name* PATH_MESH_ICON_EXPAND_DOWN = nullptr;
const Name* PATH_MESH_ICON_DROPDOWN = nullptr;
const Name* PATH_MESH_ASSET_ICON_VFX = nullptr;
const Name* PATH_MESH_ASSET_ICON_SOUND = nullptr;
const Name* PATH_MESH_ASSET_ICON_SHADER = nullptr;
const Name* PATH_MESH_ASSET_ICON_LUA = nullptr;
const Name* PATH_MESH_ASSET_ICON_FONT = nullptr;

// @load
bool LoadAssets(Allocator* allocator)
{
    // @name
    NAME_MESH = GetName("mesh");
    NAME_VFX = GetName("vfx");
    NAME_ANIMATION = GetName("animation");
    NAME_ATLAS = GetName("atlas");
    NAME_M = GetName("m");
    NAME_ANIMATEDMESH = GetName("animatedmesh");
    NAME_EDIT = GetName("edit");
    NAME_RENAME = GetName("rename");
    NAME_N = GetName("n");
    NAME_S = GetName("s");
    NAME_SAVE = GetName("save");
    NAME_AM = GetName("am");
    NAME_BUILD = GetName("build");
    NAME_EVENT = GetName("event");
    NAME_E = GetName("e");
    NAME_NEW = GetName("new");
    NAME_R = GetName("r");
    NAME_B = GetName("b");
    NAME_MIRROR = GetName("mirror");
    NAME_SKELETON = GetName("skeleton");
    NAME_RU = GetName("ru");
    NAME_A = GetName("a");

    // @path
    PATH_MESH_ASSET_ICON_BIN = GetName("asset_icon_bin");
    PATH_MESH_ICON_PALETTE = GetName("icon_palette");
    PATH_FONT_SEGUISB = GetName("seguisb");
    PATH_TEXTURE_TEST = GetName("test");
    PATH_SHADER_VFX = GetName("vfx");
    PATH_SHADER_UI_VIGNETTE = GetName("ui_vignette");
    PATH_SHADER_UI_IMAGE_TEXTURE = GetName("ui_image_texture");
    PATH_SHADER_UI_IMAGE = GetName("ui_image");
    PATH_SHADER_UI = GetName("ui");
    PATH_SHADER_TEXTURED_MESH = GetName("textured_mesh");
    PATH_SHADER_TEXT = GetName("text");
    PATH_SHADER_SOLID = GetName("solid");
    PATH_SHADER_SKINNED_MESH = GetName("skinned_mesh");
    PATH_SHADER_POSTPROCESS_UI_COMPOSITE = GetName("postprocess_ui_composite");
    PATH_SHADER_POSTPROCESS_DESATURATE = GetName("postprocess_desaturate");
    PATH_TEXTURE_EDITOR_PALETTE = GetName("editor_palette");
    PATH_MESH_ASSET_ICON_EVENT = GetName("asset_icon_event");
    PATH_SHADER_MESH = GetName("mesh");
    PATH_SHADER_EDITOR = GetName("editor");
    PATH_MESH_ICON_TILING = GetName("icon_tiling");
    PATH_MESH_ICON_ROOT_MOTION = GetName("icon_root_motion");
    PATH_MESH_ICON_PUBLISH = GetName("icon_publish");
    PATH_MESH_ICON_ONION = GetName("icon_onion");
    PATH_MESH_ICON_MIRROR = GetName("icon_mirror");
    PATH_MESH_ICON_LOOP = GetName("icon_loop");
    PATH_MESH_ICON_EXPAND_UP = GetName("icon_expand_up");
    PATH_MESH_ICON_EXPAND_DOWN = GetName("icon_expand_down");
    PATH_MESH_ICON_DROPDOWN = GetName("icon_dropdown");
    PATH_MESH_ASSET_ICON_VFX = GetName("asset_icon_vfx");
    PATH_MESH_ASSET_ICON_SOUND = GetName("asset_icon_sound");
    PATH_MESH_ASSET_ICON_SHADER = GetName("asset_icon_shader");
    PATH_MESH_ASSET_ICON_LUA = GetName("asset_icon_lua");
    PATH_MESH_ASSET_ICON_FONT = GetName("asset_icon_font");

    // @Mesh
    NOZ_LOAD_MESH(allocator, PATH_MESH_ASSET_ICON_BIN, MESH_ASSET_ICON_BIN);
    NOZ_LOAD_MESH(allocator, PATH_MESH_ICON_PALETTE, MESH_ICON_PALETTE);
    NOZ_LOAD_MESH(allocator, PATH_MESH_ASSET_ICON_EVENT, MESH_ASSET_ICON_EVENT);
    NOZ_LOAD_MESH(allocator, PATH_MESH_ICON_TILING, MESH_ICON_TILING);
    NOZ_LOAD_MESH(allocator, PATH_MESH_ICON_ROOT_MOTION, MESH_ICON_ROOT_MOTION);
    NOZ_LOAD_MESH(allocator, PATH_MESH_ICON_PUBLISH, MESH_ICON_PUBLISH);
    NOZ_LOAD_MESH(allocator, PATH_MESH_ICON_ONION, MESH_ICON_ONION);
    NOZ_LOAD_MESH(allocator, PATH_MESH_ICON_MIRROR, MESH_ICON_MIRROR);
    NOZ_LOAD_MESH(allocator, PATH_MESH_ICON_LOOP, MESH_ICON_LOOP);
    NOZ_LOAD_MESH(allocator, PATH_MESH_ICON_EXPAND_UP, MESH_ICON_EXPAND_UP);
    NOZ_LOAD_MESH(allocator, PATH_MESH_ICON_EXPAND_DOWN, MESH_ICON_EXPAND_DOWN);
    NOZ_LOAD_MESH(allocator, PATH_MESH_ICON_DROPDOWN, MESH_ICON_DROPDOWN);
    NOZ_LOAD_MESH(allocator, PATH_MESH_ASSET_ICON_VFX, MESH_ASSET_ICON_VFX);
    NOZ_LOAD_MESH(allocator, PATH_MESH_ASSET_ICON_SOUND, MESH_ASSET_ICON_SOUND);
    NOZ_LOAD_MESH(allocator, PATH_MESH_ASSET_ICON_SHADER, MESH_ASSET_ICON_SHADER);
    NOZ_LOAD_MESH(allocator, PATH_MESH_ASSET_ICON_LUA, MESH_ASSET_ICON_LUA);
    NOZ_LOAD_MESH(allocator, PATH_MESH_ASSET_ICON_FONT, MESH_ASSET_ICON_FONT);

    static Mesh* _MESH[] = {
        MESH_ASSET_ICON_BIN,
        MESH_ICON_PALETTE,
        MESH_ASSET_ICON_EVENT,
        MESH_ICON_TILING,
        MESH_ICON_ROOT_MOTION,
        MESH_ICON_PUBLISH,
        MESH_ICON_ONION,
        MESH_ICON_MIRROR,
        MESH_ICON_LOOP,
        MESH_ICON_EXPAND_UP,
        MESH_ICON_EXPAND_DOWN,
        MESH_ICON_DROPDOWN,
        MESH_ASSET_ICON_VFX,
        MESH_ASSET_ICON_SOUND,
        MESH_ASSET_ICON_SHADER,
        MESH_ASSET_ICON_LUA,
        MESH_ASSET_ICON_FONT,
        nullptr
    };

    MESH = _MESH;
    MESH_COUNT = sizeof(_MESH) / sizeof(void*);

    // @Texture
    NOZ_LOAD_TEXTURE(allocator, PATH_TEXTURE_TEST, TEXTURE_TEST);
    NOZ_LOAD_TEXTURE(allocator, PATH_TEXTURE_EDITOR_PALETTE, TEXTURE_EDITOR_PALETTE);

    static Texture* _TEXTURE[] = {
        TEXTURE_TEST,
        TEXTURE_EDITOR_PALETTE,
        nullptr
    };

    TEXTURE = _TEXTURE;
    TEXTURE_COUNT = sizeof(_TEXTURE) / sizeof(void*);

    // @Font
    NOZ_LOAD_FONT(allocator, PATH_FONT_SEGUISB, FONT_SEGUISB);

    static Font* _FONT[] = {
        FONT_SEGUISB,
        nullptr
    };

    FONT = _FONT;
    FONT_COUNT = sizeof(_FONT) / sizeof(void*);

    // @Shader
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_VFX, SHADER_VFX);
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_UI_VIGNETTE, SHADER_UI_VIGNETTE);
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_UI_IMAGE_TEXTURE, SHADER_UI_IMAGE_TEXTURE);
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_UI_IMAGE, SHADER_UI_IMAGE);
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_UI, SHADER_UI);
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_TEXTURED_MESH, SHADER_TEXTURED_MESH);
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_TEXT, SHADER_TEXT);
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_SOLID, SHADER_SOLID);
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_SKINNED_MESH, SHADER_SKINNED_MESH);
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_POSTPROCESS_UI_COMPOSITE, SHADER_POSTPROCESS_UI_COMPOSITE);
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_POSTPROCESS_DESATURATE, SHADER_POSTPROCESS_DESATURATE);
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_MESH, SHADER_MESH);
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_EDITOR, SHADER_EDITOR);

    static Shader* _SHADER[] = {
        SHADER_VFX,
        SHADER_UI_VIGNETTE,
        SHADER_UI_IMAGE_TEXTURE,
        SHADER_UI_IMAGE,
        SHADER_UI,
        SHADER_TEXTURED_MESH,
        SHADER_TEXT,
        SHADER_SOLID,
        SHADER_SKINNED_MESH,
        SHADER_POSTPROCESS_UI_COMPOSITE,
        SHADER_POSTPROCESS_DESATURATE,
        SHADER_MESH,
        SHADER_EDITOR,
        nullptr
    };

    SHADER = _SHADER;
    SHADER_COUNT = sizeof(_SHADER) / sizeof(void*);

    return true;
}

// @unload
void UnloadAssets()
{
    // @Mesh
    Free(MESH_ASSET_ICON_BIN);
    Free(MESH_ICON_PALETTE);
    Free(MESH_ASSET_ICON_EVENT);
    Free(MESH_ICON_TILING);
    Free(MESH_ICON_ROOT_MOTION);
    Free(MESH_ICON_PUBLISH);
    Free(MESH_ICON_ONION);
    Free(MESH_ICON_MIRROR);
    Free(MESH_ICON_LOOP);
    Free(MESH_ICON_EXPAND_UP);
    Free(MESH_ICON_EXPAND_DOWN);
    Free(MESH_ICON_DROPDOWN);
    Free(MESH_ASSET_ICON_VFX);
    Free(MESH_ASSET_ICON_SOUND);
    Free(MESH_ASSET_ICON_SHADER);
    Free(MESH_ASSET_ICON_LUA);
    Free(MESH_ASSET_ICON_FONT);

    // @Texture
    Free(TEXTURE_TEST);
    Free(TEXTURE_EDITOR_PALETTE);

    // @Font
    Free(FONT_SEGUISB);

    // @Shader
    Free(SHADER_VFX);
    Free(SHADER_UI_VIGNETTE);
    Free(SHADER_UI_IMAGE_TEXTURE);
    Free(SHADER_UI_IMAGE);
    Free(SHADER_UI);
    Free(SHADER_TEXTURED_MESH);
    Free(SHADER_TEXT);
    Free(SHADER_SOLID);
    Free(SHADER_SKINNED_MESH);
    Free(SHADER_POSTPROCESS_UI_COMPOSITE);
    Free(SHADER_POSTPROCESS_DESATURATE);
    Free(SHADER_MESH);
    Free(SHADER_EDITOR);
}

#ifdef NOZ_LUA
void BindLuaAssets(noz::lua::State* state) {
    using namespace noz::lua;

    // Mesh
    SetGlobal(state, "MESH_ASSET_ICON_BIN", MESH_ASSET_ICON_BIN);
    SetGlobal(state, "MESH_ICON_PALETTE", MESH_ICON_PALETTE);
    SetGlobal(state, "MESH_ASSET_ICON_EVENT", MESH_ASSET_ICON_EVENT);
    SetGlobal(state, "MESH_ICON_TILING", MESH_ICON_TILING);
    SetGlobal(state, "MESH_ICON_ROOT_MOTION", MESH_ICON_ROOT_MOTION);
    SetGlobal(state, "MESH_ICON_PUBLISH", MESH_ICON_PUBLISH);
    SetGlobal(state, "MESH_ICON_ONION", MESH_ICON_ONION);
    SetGlobal(state, "MESH_ICON_MIRROR", MESH_ICON_MIRROR);
    SetGlobal(state, "MESH_ICON_LOOP", MESH_ICON_LOOP);
    SetGlobal(state, "MESH_ICON_EXPAND_UP", MESH_ICON_EXPAND_UP);
    SetGlobal(state, "MESH_ICON_EXPAND_DOWN", MESH_ICON_EXPAND_DOWN);
    SetGlobal(state, "MESH_ICON_DROPDOWN", MESH_ICON_DROPDOWN);
    SetGlobal(state, "MESH_ASSET_ICON_VFX", MESH_ASSET_ICON_VFX);
    SetGlobal(state, "MESH_ASSET_ICON_SOUND", MESH_ASSET_ICON_SOUND);
    SetGlobal(state, "MESH_ASSET_ICON_SHADER", MESH_ASSET_ICON_SHADER);
    SetGlobal(state, "MESH_ASSET_ICON_LUA", MESH_ASSET_ICON_LUA);
    SetGlobal(state, "MESH_ASSET_ICON_FONT", MESH_ASSET_ICON_FONT);

    // Texture
    SetGlobal(state, "TEXTURE_TEST", TEXTURE_TEST);
    SetGlobal(state, "TEXTURE_EDITOR_PALETTE", TEXTURE_EDITOR_PALETTE);

    // Font
    SetGlobal(state, "FONT_SEGUISB", FONT_SEGUISB);

    // Shader
    SetGlobal(state, "SHADER_VFX", SHADER_VFX);
    SetGlobal(state, "SHADER_UI_VIGNETTE", SHADER_UI_VIGNETTE);
    SetGlobal(state, "SHADER_UI_IMAGE_TEXTURE", SHADER_UI_IMAGE_TEXTURE);
    SetGlobal(state, "SHADER_UI_IMAGE", SHADER_UI_IMAGE);
    SetGlobal(state, "SHADER_UI", SHADER_UI);
    SetGlobal(state, "SHADER_TEXTURED_MESH", SHADER_TEXTURED_MESH);
    SetGlobal(state, "SHADER_TEXT", SHADER_TEXT);
    SetGlobal(state, "SHADER_SOLID", SHADER_SOLID);
    SetGlobal(state, "SHADER_SKINNED_MESH", SHADER_SKINNED_MESH);
    SetGlobal(state, "SHADER_POSTPROCESS_UI_COMPOSITE", SHADER_POSTPROCESS_UI_COMPOSITE);
    SetGlobal(state, "SHADER_POSTPROCESS_DESATURATE", SHADER_POSTPROCESS_DESATURATE);
    SetGlobal(state, "SHADER_MESH", SHADER_MESH);
    SetGlobal(state, "SHADER_EDITOR", SHADER_EDITOR);
}

#endif

#if !defined(NOZ_BUILTIN_ASSETS)

void HotloadAsset(const Name* incoming_name, AssetType incoming_type)
{
    // @Mesh
    NOZ_RELOAD_MESH(PATH_MESH_ASSET_ICON_BIN, MESH_ASSET_ICON_BIN);
    NOZ_RELOAD_MESH(PATH_MESH_ICON_PALETTE, MESH_ICON_PALETTE);
    NOZ_RELOAD_MESH(PATH_MESH_ASSET_ICON_EVENT, MESH_ASSET_ICON_EVENT);
    NOZ_RELOAD_MESH(PATH_MESH_ICON_TILING, MESH_ICON_TILING);
    NOZ_RELOAD_MESH(PATH_MESH_ICON_ROOT_MOTION, MESH_ICON_ROOT_MOTION);
    NOZ_RELOAD_MESH(PATH_MESH_ICON_PUBLISH, MESH_ICON_PUBLISH);
    NOZ_RELOAD_MESH(PATH_MESH_ICON_ONION, MESH_ICON_ONION);
    NOZ_RELOAD_MESH(PATH_MESH_ICON_MIRROR, MESH_ICON_MIRROR);
    NOZ_RELOAD_MESH(PATH_MESH_ICON_LOOP, MESH_ICON_LOOP);
    NOZ_RELOAD_MESH(PATH_MESH_ICON_EXPAND_UP, MESH_ICON_EXPAND_UP);
    NOZ_RELOAD_MESH(PATH_MESH_ICON_EXPAND_DOWN, MESH_ICON_EXPAND_DOWN);
    NOZ_RELOAD_MESH(PATH_MESH_ICON_DROPDOWN, MESH_ICON_DROPDOWN);
    NOZ_RELOAD_MESH(PATH_MESH_ASSET_ICON_VFX, MESH_ASSET_ICON_VFX);
    NOZ_RELOAD_MESH(PATH_MESH_ASSET_ICON_SOUND, MESH_ASSET_ICON_SOUND);
    NOZ_RELOAD_MESH(PATH_MESH_ASSET_ICON_SHADER, MESH_ASSET_ICON_SHADER);
    NOZ_RELOAD_MESH(PATH_MESH_ASSET_ICON_LUA, MESH_ASSET_ICON_LUA);
    NOZ_RELOAD_MESH(PATH_MESH_ASSET_ICON_FONT, MESH_ASSET_ICON_FONT);

    // @Texture
    NOZ_RELOAD_TEXTURE(PATH_TEXTURE_TEST, TEXTURE_TEST);
    NOZ_RELOAD_TEXTURE(PATH_TEXTURE_EDITOR_PALETTE, TEXTURE_EDITOR_PALETTE);

    // @Font
    NOZ_RELOAD_FONT(PATH_FONT_SEGUISB, FONT_SEGUISB);

    // @Shader
    NOZ_RELOAD_SHADER(PATH_SHADER_VFX, SHADER_VFX);
    NOZ_RELOAD_SHADER(PATH_SHADER_UI_VIGNETTE, SHADER_UI_VIGNETTE);
    NOZ_RELOAD_SHADER(PATH_SHADER_UI_IMAGE_TEXTURE, SHADER_UI_IMAGE_TEXTURE);
    NOZ_RELOAD_SHADER(PATH_SHADER_UI_IMAGE, SHADER_UI_IMAGE);
    NOZ_RELOAD_SHADER(PATH_SHADER_UI, SHADER_UI);
    NOZ_RELOAD_SHADER(PATH_SHADER_TEXTURED_MESH, SHADER_TEXTURED_MESH);
    NOZ_RELOAD_SHADER(PATH_SHADER_TEXT, SHADER_TEXT);
    NOZ_RELOAD_SHADER(PATH_SHADER_SOLID, SHADER_SOLID);
    NOZ_RELOAD_SHADER(PATH_SHADER_SKINNED_MESH, SHADER_SKINNED_MESH);
    NOZ_RELOAD_SHADER(PATH_SHADER_POSTPROCESS_UI_COMPOSITE, SHADER_POSTPROCESS_UI_COMPOSITE);
    NOZ_RELOAD_SHADER(PATH_SHADER_POSTPROCESS_DESATURATE, SHADER_POSTPROCESS_DESATURATE);
    NOZ_RELOAD_SHADER(PATH_SHADER_MESH, SHADER_MESH);
    NOZ_RELOAD_SHADER(PATH_SHADER_EDITOR, SHADER_EDITOR);
}

#endif
